### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by CQUPT-CaiKe** [QZx7/MindTheTime#6]
Dear authors, I was very interested after reading your work. But I didn't find any description about the startup code. Please forgive me for being a beginner, can you tell me the detailed code startup method, I would be grateful.

**Comment by QZx7** [comment]
@CQUPT-CaiKe Hi, this repo contains the code for our data collection system and the dataset. For training a model, we used ParlAI framework: https://parl.ai/ . If you are familiar with the ParlAI (you might need to spend some time learning the framework if you are not familiar with it), it should be just converting the dataset to the required format and start the training with one simple command. We do not serve the model due to cost issues, however, we provide the train/test split of the dataset.

** Chatting service
So, if you want to run the data collection server, what you need to do are:
- create a virtual python env.
- install tornado `pip install tornado`.
- enter `mtt/chat` and run `python event_chat.py`
- on your browser, go to`localhost:8888?workerId=000`

And you should be able to see the instructions and the `start matching` button. Hit the start matching button and the work with Id=000 will join the match queue.
Do the same thing on a new browser tab and go to `localhost:8888?workerId=001` for another instance. After you have more than two workers in the queue, a couple of them will be directed into the chatting room.

Events, progress are loaded from the json files under `mtt/chat/data/events`. You can customize your own events with the same format.

** Model training
With the data files under `mtt/chat/data/gap_chat`, you can convert the dialogue data into ParlAI format. You can refer to `mtt/data_collection/prepare_data.py` for how we treat the events and dialogues. Then you can simply run the training command within ParlAI by loading data from local file. It is possible to play with whatever model that is available in the model zoo. However, if you want to train the RAG model, you might need to create the index first. We follow the steps as described in: https://parl.ai/docs/agent_refs/rag.html and use DPR model. However, the DPR repo has been archived by Meta it might be possible to use some other methods. You may also fine-tune the model on existing MSC models https://parl.ai/docs/zoo.html#msc-models without indexing. However, the performance may not be as good as creating some new index.

**Comment by CQUPT-CaiKe** [comment]
![image](https://github.com/user-attachments/assets/50a44c42-96d3-4020-811c-8ceb79850fe5)
Sorry, something maybe wrongs?

**Comment by QZx7** [comment]
@CQUPT-CaiKe This version is specifically designed for running on AMT. So it requires another couple of arguments.
Can you try accessing `localhost:8888?workerId=000&assignmentId=somerandomassignmentId&hitId=somerandomhitId`?

**Comment by CQUPT-CaiKe** [comment]
Thanks. The other question is that it can not match other workers. I try different wokerID and wait matching, but it does not match. Such as localhost:8888?workerId=000&assignmentId=001&hitId=002, localhost:8888?workerId=006&assignmentId=001&hitId=002, and localhost:8888?workerId=003&assignmentId=002&hitId=004.

**Comment by QZx7** [comment]
Can you share the log data you got on the server side?
Normally, you should be able to see logs like this:
```
[Log] 001 Joined
[Log] Worker: 000 started matching.
[Log] matching queue: ['000']
[Log] Worker: 001 started matching.
[Log] matching queue: ['000', '001']
[Log] matched, room_info: {'room_id': 0, 'speaker_1': '001', 'speaker_2': '000', 'save_location': 'd:\\project\\MindTheTime\\mtt\\chat\\log\\20241219-115116-0.log'}
[Log] Room 0 is initialed
```

**Comment by CQUPT-CaiKe** [comment]
[I 241219 10:55:50 web:2239] 304 GET /?workerId=000&assignmentId=001&hitId=002 (::1) 10.03ms
[I 241219 10:55:50 web:2239] 101 GET /match (::1) 0.00ms
[Log] 000 Joined
[Log] Worker: 000 started matching.
[Log] matching queue: ['000']
[I 241219 10:56:20 web:2239] 304 GET /?workerId=001&assignmentId=001&hitId=002 (::1) 6.29ms
[I 241219 10:56:20 web:2239] 101 GET /match (::1) 0.00ms
[Log] 001 Joined
[Log] Worker: 001 started matching.
[Log] matching queue: ['000', '001']
[E 241219 10:56:22 ioloop:761] Exception in callback functools.partial(<function WebSocketProtocol._run_callback.<locals>.<lambda> at 0x000001A7F82D7E50>, <Task finished name='Task-17' coro=<MatchHandler.on_message() done, defined at event_chat.py:457> exception=FileNotFoundError(2, 'No such file or directory')>)
    Traceback (most recent call last):
      File "C:\Python\Anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
        ret = callback()
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 656, in <lambda>
        self.stream.io_loop.add_future(result, lambda f: f.result())
      File "event_chat.py", line 477, in on_message
        room_info = await ioloop.IOLoop.current().run_in_executor(
      File "C:\Python\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "event_chat.py", line 308, in match
        f = open(save_location, "a")
    FileNotFoundError: [Errno 2] No such file or directory: 'log\\20241219-105529-0.log'
[E 241219 10:56:22 web:1789] Uncaught exception GET /match (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/match', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Python\Anaconda3\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 278, in get
        await self.ws_connection.accept_connection(self)
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 879, in accept_connection
        await self._accept_connection(handler)
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 962, in _accept_connection
        await self._receive_frame_loop()
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 1116, in _receive_frame_loop
        await self._receive_frame()
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 1207, in _receive_frame
        await handled_future
      File "C:\Python\Anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
        ret = callback()
      File "C:\Python\Anaconda3\lib\site-packages\tornado\websocket.py", line 656, in <lambda>
        self.stream.io_loop.add_future(result, lambda f: f.result())
      File "event_chat.py", line 477, in on_message
        room_info = await ioloop.IOLoop.current().run_in_executor(
      File "C:\Python\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "event_chat.py", line 308, in match
        f = open(save_location, "a")
    FileNotFoundError: [Errno 2] No such file or directory: 'log\\20241219-105529-0.log'

**Comment by QZx7** [comment]
@CQUPT-CaiKe I think it's because the system was not able to create the log folder. We removed this to protect workers privacy.

You could try manually creating a log folder with the following steps:
- go to `mtt/chat` folder
- create a new folder `log`

Then you should be able to do the matching.
